### ISSUE TITLE
Form submission not working due to layout: false

### ISSUE THREAD

**Issue by til** [gregmolnar/dependent-dropdown#1]
The demo app works as expected in that after loading the fixtures, one can go to /addresses/new and when selecting an entry from the country dropdown, e.g. "United Kingdom", the state dropdown is automatically updated with the list of corresponding states.

When trying to submit the form with "Create Address", one would expect it to reload the form with validation errors in red on top, and still the same country selected. However, it triggers a 422 response followed by a 200 which loads a blank /addresses/new, without validation errors and no country selected.

The reason is that the first request does not conform to `turbo-rails`'s expectation, so it GETs the page again. The current version of `turbo-rails` uses its own layout: https://github.com/hotwired/turbo-rails#a-note-on-custom-layouts, so in

https://github.com/gregmolnar/dependent-dropdown/blob/main/app/controllers/addresses_controller.rb#L31

the `layout: !request.format.turbo_stream?` part confuses it.

Removing this part makes the form submission behave as expected.

@gregmolnar I know this is only a little demo app for a blog post and don't want to bother you with overly detailed bug reports. But maybe you want to update it nevertheless, since that piece of the code is also included in the blog post – someone who is not so familiar with turbo and follows the blog post step by step might get confused.

**Comment by gregmolnar** [comment]
@til thanks for the report! I will change the app and the blogpost.

**Comment by gregmolnar** [comment]
@til I finally had time to look into this. The issue is not the layout, but that the turboframe doesn't wrap the whole form, so on submit validation errors were not displayed and city was required and wasn't set because cities were not loaded.
I updated the code in the repository and I am updating the code example in the blog post.
Thanks again for reporting!

**Comment by til** [comment]
You're right, the conditional layout wasn't the culprit. After the latest change the validation errors are now displayed after invalid form submission as expected, that's great.

A smaller problem with this approach is that now, when selecting a country from the dropdown it also triggers an invalid form submission, resulting in validation errors being displayed as well:

![new-address](https://github.com/gregmolnar/dependent-dropdown/assets/11211/904e0b95-b9c2-4d30-8fe9-492b2a0355af)

Anyway, maybe a motivation for another blog post one day.

I found that getting Turbo to work with forms in situations like these can be tricky, so blog posts like yours help me a lot wrapping my head around it, thanks!

**Comment by gregmolnar** [comment]
@til that's a good point, the dropdown should target that frame. I will write a follow-up for that.
